### ISSUE TITLE
Unimplemented `(reflect.Type).NumMethod()` when Unmarshalling v1.Pod

### ISSUE THREAD

**Issue by viccuad** [kubewarden/k8s-objects#5] opened 2022-08-12 08:06 UTC
It seems that in some case, using `easyjson` and `kubewarden/k8s-objects` calls a `reflect` function, which is unimplemented in Tinygo.

## Reproducer:

As hit in policy https://github.com/jparrill/safe-naming-policy  from community ([commit with change away from easyjson and into gjson](https://github.com/jparrill/safe-naming-policy/commit/b7165647416736547bbdb2afee6048d1674b9fa3))

When validating an invalid pod, we get a `panic: unimplemented: (reflect.Type).NumMethod()`.

Investigate why Reflect is being used in this case.

See also the [Slack conversation](https://kubernetes.slack.com/archives/C01T3GTC3L7/p1660229102638299?thread_ts=1660229060.024139&cid=C01T3GTC3L7).

**Comment by flavio** [comment] 2022-09-01 16:36
I was able to reproduce the issue using a checkout of the policy done before @jparrill switched to gjson. I basically used [this tree](https://github.com/jparrill/safe-naming-policy/tree/e06f42c60954d632ab81ca1f5ebec3568ed4d173).

Long story short, the reflection error is caused by the datetime objects found inside of the Pod, more specifically:
  * `metadata.creationTimestamp`
  * `metadata.managedFields[0].time`

Both attributes are not set inside of the [sample pod](https://github.com/jparrill/safe-naming-policy/blob/e06f42c60954d632ab81ca1f5ebec3568ed4d173/assets/test_data/pod.json) used by the e2e tests. That's why the issue was detected only inside of Kubernetes.

The runtime panic has already been fixed inside of [kubewarden/strfmt:v0.1.1](https://github.com/kubewarden/strfmt/releases/tag/v0.1.1). Other corner cases have been addressed with the [latest release](https://github.com/kubewarden/strfmt/releases/tag/v0.1.2).

The `go.mod` of @jparrill's policy was still [referencing the 0.1.0 release](https://github.com/jparrill/safe-naming-policy/blob/e06f42c60954d632ab81ca1f5ebec3568ed4d173/go.mod#L23).
Rebuilding the policy with strfmt v0.1.2 fixes the issue.

I've already double checked our go policy template, which is referencing the right version of the strfmt library. Probably @jparrill started from an older template?

Closing as fixed.

**Closed as completed by flavio** 2022-09-01 16:36 UTC
